"""Initial database schema

Revision ID: 04014e136a71
Revises:
Create Date: 2025-07-29 14:02:33.886312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04014e136a71"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "psychologists",
        sa.Column("qualification", sa.String(length=128), nullable=False),
        sa.Column("specialization", sa.String(length=128), nullable=True),
        sa.Column("license_number", sa.String(length=32), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "clients",
        sa.Column("alias", sa.String(length=32), nullable=False),
        sa.Column("psychologist_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("last_name", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["psychologist_id"],
            ["psychologists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "mood_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column(
            "mood_level",
            sa.Enum(
                "VERY_BAD",
                "BAD",
                "NEUTRAL",
                "GOOD",
                "EXCELLENT",
                name="mood_level",
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("analyzed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emotion_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("emotions", sa.JSON(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("insights", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["mood_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entry_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "WORK",
                "EXERCISE",
                "SOCIAL",
                "HOBBY",
                "REST",
                "LEARNING",
                "MEDITATION",
                name="activity_type",
            ),
            nullable=False,
        ),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["mood_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entry_triggers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "WORK",
                "RELATIONSHIPS",
                "HEALTH",
                "FINANCE",
                "FAMILY",
                "SOCIAL",
                "SELF_CARE",
                name="trigger_type",
            ),
            nullable=False,
        ),
        sa.Column("intensity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["mood_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "psychologist_feedbacks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("psychologist_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("feedback_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["mood_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["psychologist_id"],
            ["psychologists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("psychologist_feedbacks")
    op.drop_table("entry_triggers")
    op.drop_table("entry_activities")
    op.drop_table("emotion_analyses")
    op.drop_table("mood_entries")
    op.drop_table("clients")
    op.drop_table("psychologists")
    # ### end Alembic commands ###
